Saturday, 14 September 2013
===================================

I'm trying to figure out how to mock an EloquentRepository class... Having a challenging time. 

In the service provider, I register it like so:

```php
    public function register()
    {
        $this->app['kalani-object'] = $this->app->share(function($app){
            return new \Kalani\Core\Object\EloquentObjectRepository(
                new \Kalani\Core\Object\Object
            );
        });

        $this->app->bind('Kalani\Core\Object\ObjectRepositoryInterface', function() {
            return new \Kalani\Core\Object\EloquentObjectRepository(
                new \Kalani\Core\Object\Object
            );
        });
    }
```

In my tester, I want to mock it like so:

```php
    public function testFoo()
    {
        $mock = \Mockery::mock('\Kalani\Core\Object\ObjectRepositoryInterface');
        app()->instance('\Kalani\Core\Object\ObjectRepositoryInterface', $mock);
        $mock->shouldReceive('create')->once()->andReturn('foo');

        $this->test->foo();
    }
```

And, in my class under test, I have this:

```php
    public function foo()
    {
        $obj = app('kalani-object');
        dd($obj);
    }
```

It's picking up a standard Kalani\Core\Object\EloquentObjectRepository object, rather than my mock object. It seems to be going to ObjectServiceProvider::register, and loading the object from there.

Hmmmm....

This seems to work:

    $this->app->instance('kalani-object', $mock);

So, go off of $this->app->instance, rather than a global app()->instance.



Sunday, 15 September 2013
===================================

I'm having a problem with a codeception test. Basically, I want to make sure I can get an error message. Here's my test:

```php
    public function testValidationReturnsErrorMessages(WebGuy $I)
    {
        $I->am('a person allowed to edit people\'s information');
        $I->wantTo('update a record with invalid data to see the resulting error');
        $I->amOnPage('api/people/45/edit');
        $I->fillField('[name="birthdate"]', 'Test');
        $I->click('Save changes');
        $I->see('not a valid date');
    }
```

It doesn't seem to be following the redirect, in codeception. It works fine in a browser, though. My controller looks like this:

```php
    public function update($oid)
    {
        if ($this->person->update($oid)) {
            return Redirect::route('api.people.show', $oid)
                ->with('success', 'changes saved');            
        }

        return Redirect::route('api.people.edit', $oid)
            ->withInput()
            ->withErrors($this->person->errors());
    }    
```

Actually, the redirection seems to be working fine, but the session data seems to be getting lost.... Or just the error data, itself.

Session::get('error') is returning a value. It looks like Session::get('success') is also returning a value, from a previous test.

And Session::get('errors') returns nothing.

It might be coming through my routing....

    GET api/person/45/edit
    PUT api/person/45
    GET objects/45/edit
    ...which GETs api/person/45/edit

It could potentially lose session data there...

No. It has the error until it opens the view... And then the error is gone... Just in codeception, not another browser.

I set my `edit` function to this, to clarify what's happening:

```php
    public function edit($oid)
    {
        echo('A>');
        var_dump(Session::get('errors'));
        echo('B>');
        $found = $this->person->findOid($oid);
        return View::make('frontend.object.person.edit')
            ->with('person', $found);
    }
```

The first line of my view is `{{ var_dump($errors) }}`, so I would expect to see the lines after A> and B> to both have the same information. When I run it in a browser, I get what I expect:

> A>
> object(Illuminate\Support\MessageBag)[111]
>   protected 'messages' => 
>     array
>       'birthdate' => 
>         array
>           0 => string 'The birthdate is not a valid date.' (length=34)
>   protected 'format' => string ':message' (length=8)
> B>
> object(Illuminate\Support\MessageBag)[111]
>   protected 'messages' => 
>     array
>       'birthdate' => 
>         array
>           0 => string 'The birthdate is not a valid date.' (length=34)
>   protected 'format' => string ':message' (length=8)

When I run `codecept run --steps`; though, I get this:

> * I click "Save changes"
> A>object(Illuminate\Support\MessageBag)#899 (2) {
>   ["messages":protected]=>
>   array(1) {
>     ["birthdate"]=>
>     array(1) {
>       [0]=>
>       string(34) "The birthdate is not a valid date."
>     }
>   }
>   ["format":protected]=>
>   string(8) ":message"
> }
> B>* I see "Please check the form below for errors"
>    FAILED 

At the beginning of the log file, I see what the view is receiving:

> object(Illuminate\Support\MessageBag)#483 (2) {
>   ["messages":protected]=>
>   array(0) {
>   }
>   ["format":protected]=>
>   string(8) ":message"
> }

Hmmm.... If I change the view to call `{{ var_dump(Session::get('errors')) }}`, it works. Somehow $errors is different than Session::get('errors').

